config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'count#input', as: 'home'
  get '/count/result', to: 'count#result'
  get '/count/input', to: 'count#input'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/count_controller.rb
# frozen_string_literal: true

# Count Controller
class CountController < ApplicationController
  include CountHelper
  before_action :validate_string, only: :result
  def input; end

  def result
    @result_array = squares(@array)
  end

  private

  def validate_string
    @string = params[:string_array]
    @count = params[:number].to_i
    @array = @string.split.map(&:to_i)
    if /[^\d^\s^]/.match(@string)
      redirect_to home_path, alert: 'Вводите только числа и пробелы'
    elsif @count != @array.size
      redirect_to home_path, alert: 'N не равно количеству чисел'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/count_helper.rb
module CountHelper
  def squares(array)
    result_array = []
    array.each_with_index do |n, i|
      if  Math.sqrt(n).to_r.denominator == 1
        temp_array = array.slice(i, array.size - i)
        res = temp_array.take_while { |temp| Math.sqrt(temp).to_r.denominator == 1 }
        result_array.push(res)
      end
    end
    result_array
  end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/count/input.html.erb
<%= form_with url: '/count/result', method: :get do |form| %>
  <div>
    <%= form.label :number, "Input n", style: "display:block" %>
    <%= form.number_field :number, min: 1 %>
  </div>
  </br>
  <div>
  <%= form.label :string_array, "Input numbers", style: "display:block" %>
  <%= form.text_field :string_array, style: "width:300px" %>
  </div>
  </br>
  <div>
    <%= form.submit "Check Result" %>
  </div>
<% end %>
<div>
    <%flash.each do |type,msg| %>
      <div> <%= msg %> </div>
    <% end %>
</div>

app/views/count/result.html.erb
<% if @result_array != [] %>

  <h1>Result</h1>
  <h2>Input data: <%=@array.join(',')%></h2>
  <table border = '1'>
    <tr>
      <th style="text-align: center">Number</th>
      <th style="text-align: center">Squares</th>
    </tr>
    <% @result_array.each_with_index do |n,i| %>
      <tr>
        <td style="text-align: center"><%= i+1 %></td>
        <td style="text-align: center"><%= n.join(",") %></td>
      </tr>
    <% end %>
  </table>
  <h3>Количество последовательностей: <%= @result_array.size %></h3>
  <h3>Самая длинная последовательность: <%= @result_array.max_by(&:length).join(' ') %></h3>
  <br>
  <a href='/count/input'>Back</a>
<% else %>
 <h1>В последовательности нет квадратов</h1>
 <br>
 <a href='/count/input'>Back</a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css' %> -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= yield %>
  </body>
</html>

app/views/widgets/_form.html.erb
<%= form_with(model: widget) do |form| %>
  <% if widget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
        <% widget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/widgets/_widget.html.erb
<div id="<%= dom_id widget %>">
  <p>
    <strong>Name:</strong>
    <%= widget.name %>
  </p>

</div>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render "form", widget: @widget %>

<br>

<div>
  <%= link_to "Show this widget", @widget %> |
  <%= link_to "Back to widgets", widgets_path %>
</div>

app/views/widgets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Widgets</h1>

<div id="widgets">
  <% @widgets.each do |widget| %>
    <%= render widget %>
    <p>
      <%= link_to "Show this widget", widget %>
    </p>
  <% end %>
</div>

<%= link_to "New widget", new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render "form", widget: @widget %>

<br>

<div>
  <%= link_to "Back to widgets", widgets_path %>
</div>

app/views/widgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @widget %>

<div>
  <%= link_to "Edit this widget", edit_widget_path(@widget) %> |
  <%= link_to "Back to widgets", widgets_path %>

  <%= button_to "Destroy this widget", @widget, method: :delete %>
</div>